// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-contracts.mjs. Do not edit.
// Source digest: sha256:665f3dce2ef77dd33acc8ceea72034cd4bf9966145bc51dcab33f8cd253fc3c2

#![allow(clippy::doc_markdown, clippy::large_enum_variant)]

//! Canonical ExecutionPort DTOs generated from the `WinWinCode` schemas.
//! Shared scalar and domain value objects are defined once in `winwincode-domain`.

#[allow(clippy::missing_errors_doc)]
fn deserialize_required_nullable<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    <Option<T> as serde::Deserialize>::deserialize(deserializer)
}

/// Closed Control Plane action enforcement outcome.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ActionEnforcementDecision {
    #[serde(rename = "permit")]
    Permit,
    #[serde(rename = "reject")]
    Reject,
}

/// Immutable Control Plane-issued action receipt bound to tenant, actor, Policy version, invocation, action digest, and current Worker authority.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ActionEnforcementReceiptMessageKind {
    #[serde(rename = "action.enforcement_receipt")]
    ActionEnforcementReceipt,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ActionEnforcementReceiptMessage {
    #[serde(rename = "actor")]
    pub actor: winwincode_domain::UserActor,
    #[serde(rename = "decision")]
    pub decision: ActionEnforcementDecision,
    #[serde(rename = "evaluatedAt")]
    pub evaluated_at: winwincode_domain::Instant,
    #[serde(rename = "evaluationSha256")]
    pub evaluation_sha256: winwincode_domain::Sha256Digest,
    #[serde(rename = "jobId")]
    pub job_id: winwincode_domain::ExecutionJobId,
    #[serde(rename = "kind")]
    pub kind: ActionEnforcementReceiptMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "matchedConditionSha256")]
    pub matched_condition_sha256: Vec<winwincode_domain::Sha256Digest>,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "policyKind")]
    pub policy_kind: ActionPolicyKind,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "policyMode")]
    pub policy_mode: Option<ActionPolicyMode>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "policyVersion")]
    pub policy_version: Option<ActionPolicyVersionReference>,
    #[serde(rename = "receiptSignature")]
    pub receipt_signature: winwincode_domain::Sha256Digest,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "resource")]
    pub resource: String,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "scope")]
    pub scope: winwincode_domain::RepositoryScope,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "subjectSha256")]
    pub subject_sha256: winwincode_domain::Sha256Digest,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Requests one Control Plane Policy decision for a normalized action under current durable Worker authority.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ActionEnforcementRequestMessageKind {
    #[serde(rename = "action.enforcement_request")]
    ActionEnforcementRequest,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ActionEnforcementRequestMessage {
    #[serde(rename = "jobId")]
    pub job_id: winwincode_domain::ExecutionJobId,
    #[serde(rename = "kind")]
    pub kind: ActionEnforcementRequestMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "matchedConditionSha256")]
    pub matched_condition_sha256: Vec<winwincode_domain::Sha256Digest>,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "policyKind")]
    pub policy_kind: ActionPolicyKind,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "resource")]
    pub resource: String,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "subjectSha256")]
    pub subject_sha256: winwincode_domain::Sha256Digest,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Enterprise Policy family selected for one normalized Worker action.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ActionPolicyKind {
    #[serde(rename = "repository")]
    Repository,
    #[serde(rename = "tool")]
    Tool,
    #[serde(rename = "network")]
    Network,
}

/// Enterprise Policy enforcement mode captured by an action receipt.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ActionPolicyMode {
    #[serde(rename = "enforce")]
    Enforce,
    #[serde(rename = "audit")]
    Audit,
}

/// Exact immutable enterprise Policy version used for one action decision.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ActionPolicyVersionReference {
    #[serde(rename = "effectiveDefinitionSha256")]
    pub effective_definition_sha256: winwincode_domain::Sha256Digest,
    #[serde(rename = "policyId")]
    pub policy_id: String,
    #[serde(rename = "version")]
    pub version: i64,
    #[serde(rename = "versionDigest")]
    pub version_digest: winwincode_domain::Sha256Digest,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ActiveLeaseSummary {
    #[serde(rename = "attempt")]
    pub attempt: i64,
    #[serde(rename = "expiresAt")]
    pub expires_at: winwincode_domain::Instant,
    #[serde(rename = "fencingToken")]
    pub fencing_token: winwincode_domain::FencingToken,
    #[serde(rename = "jobId")]
    pub job_id: winwincode_domain::ExecutionJobId,
    #[serde(rename = "lastEventSequence")]
    pub last_event_sequence: winwincode_domain::ExecutionAckSequence,
    #[serde(rename = "leaseId")]
    pub lease_id: winwincode_domain::LeaseId,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ApprovalAction {
    #[serde(rename = "category")]
    pub category: ApprovalActionCategory,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "details")]
    pub details: Option<EncodedPayload>,
    #[serde(rename = "summary")]
    pub summary: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ApprovalActionCategory {
    #[serde(rename = "filesystem_write")]
    FilesystemWrite,
    #[serde(rename = "mcp")]
    Mcp,
    #[serde(rename = "network")]
    Network,
    #[serde(rename = "shell")]
    Shell,
}

/// Returns the resolved execution approval decision.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ApprovalDecisionMessageKind {
    #[serde(rename = "approval.decision")]
    ApprovalDecision,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ApprovalDecisionMessageDecision {
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "denied")]
    Denied,
    #[serde(rename = "expired")]
    Expired,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ApprovalDecisionMessageScope {
    #[serde(rename = "once")]
    Once,
    #[serde(rename = "worker_session")]
    WorkerSession,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ApprovalDecisionMessage {
    #[serde(rename = "approvalId")]
    pub approval_id: winwincode_domain::ApprovalId,
    #[serde(rename = "decidedAt")]
    pub decided_at: winwincode_domain::Instant,
    #[serde(rename = "decision")]
    pub decision: ApprovalDecisionMessageDecision,
    #[serde(rename = "kind")]
    pub kind: ApprovalDecisionMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "reason")]
    pub reason: Option<String>,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "scope")]
    pub scope: ApprovalDecisionMessageScope,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Requests a decision for one execution action; business approval state remains Control Plane owned.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ApprovalRequestMessageKind {
    #[serde(rename = "approval.request")]
    ApprovalRequest,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ApprovalRequestMessage {
    #[serde(rename = "action")]
    pub action: ApprovalAction,
    #[serde(rename = "approvalId")]
    pub approval_id: winwincode_domain::ApprovalId,
    #[serde(rename = "expiresAt")]
    pub expires_at: winwincode_domain::Instant,
    #[serde(rename = "kind")]
    pub kind: ApprovalRequestMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Acknowledges the highest contiguous artifact chunk.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ArtifactAckMessageKind {
    #[serde(rename = "artifact.ack")]
    ArtifactAck,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ArtifactAckMessage {
    #[serde(rename = "ackSequence")]
    pub ack_sequence: winwincode_domain::ExecutionAckSequence,
    #[serde(rename = "artifactId")]
    pub artifact_id: winwincode_domain::ArtifactId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "error")]
    pub error: Option<ExecutionPortError>,
    #[serde(rename = "kind")]
    pub kind: ArtifactAckMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "replayFromSequence")]
    pub replay_from_sequence: Option<winwincode_domain::ExecutionSequence>,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "status")]
    pub status: LeaseWriteStatus,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Transfers one ordered artifact chunk through either local or remote adapters.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ArtifactChunkMessageKind {
    #[serde(rename = "artifact.chunk")]
    ArtifactChunk,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ArtifactChunkMessage {
    #[serde(rename = "artifactId")]
    pub artifact_id: winwincode_domain::ArtifactId,
    #[serde(rename = "isFinal")]
    pub is_final: bool,
    #[serde(rename = "kind")]
    pub kind: ArtifactChunkMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "payload")]
    pub payload: EncodedPayload,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sequence")]
    pub sequence: winwincode_domain::ExecutionSequence,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ArtifactDescriptor {
    #[serde(rename = "artifactId")]
    pub artifact_id: winwincode_domain::ArtifactId,
    #[serde(rename = "digest")]
    pub digest: winwincode_domain::Sha256Digest,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "fileName")]
    pub file_name: Option<String>,
    #[serde(rename = "kind")]
    pub kind: ArtifactKind,
    #[serde(rename = "mediaType")]
    pub media_type: String,
    #[serde(rename = "sizeBytes")]
    pub size_bytes: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ArtifactKind {
    #[serde(rename = "candidate")]
    Candidate,
    #[serde(rename = "command_output")]
    CommandOutput,
    #[serde(rename = "diff")]
    Diff,
    #[serde(rename = "log")]
    Log,
    #[serde(rename = "report")]
    Report,
    #[serde(rename = "test_output")]
    TestOutput,
    #[serde(rename = "usage")]
    Usage,
}

/// Begins a lease-scoped artifact stream without exposing an object-store implementation.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ArtifactOpenMessageKind {
    #[serde(rename = "artifact.open")]
    ArtifactOpen,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ArtifactOpenMessage {
    #[serde(rename = "artifact")]
    pub artifact: ArtifactDescriptor,
    #[serde(rename = "kind")]
    pub kind: ArtifactOpenMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ArtifactReference {
    #[serde(rename = "artifactId")]
    pub artifact_id: winwincode_domain::ArtifactId,
    #[serde(rename = "digest")]
    pub digest: winwincode_domain::Sha256Digest,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeliveryReworkAuthorizationScope {
    #[serde(rename = "authorizationDigest")]
    pub authorization_digest: winwincode_domain::Sha256Digest,
    #[serde(rename = "candidateRef")]
    pub candidate_ref: String,
    #[serde(rename = "diffSha256")]
    pub diff_sha256: String,
    #[serde(rename = "requiresFullReverification")]
    pub requires_full_reverification: bool,
    #[serde(rename = "sourceCandidateCommitId")]
    pub source_candidate_commit_id: String,
    #[serde(rename = "sourceCandidateTreeId")]
    pub source_candidate_tree_id: String,
    #[serde(rename = "targets")]
    pub targets: Vec<DeliveryReworkTargetScope>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeliveryReworkTargetScope {
    #[serde(rename = "deliveryTaskId")]
    pub delivery_task_id: winwincode_domain::DeliveryTaskId,
    #[serde(rename = "diagramId")]
    pub diagram_id: String,
    #[serde(rename = "evidenceRefIds")]
    pub evidence_ref_ids: Vec<String>,
    #[serde(rename = "filePath")]
    pub file_path: String,
    #[serde(rename = "nodeId")]
    pub node_id: String,
    #[serde(rename = "sourceHunkSha256")]
    pub source_hunk_sha256: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeliveryStageAcceptanceCriterionInput {
    #[serde(rename = "criterionId")]
    pub criterion_id: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "required")]
    pub required: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "verificationMethod")]
    pub verification_method: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum DeliveryStageExecutionScopeKind {
    #[serde(rename = "delivery-stage")]
    DeliveryStage,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeliveryStageExecutionScope {
    #[serde(rename = "deliveryId")]
    pub delivery_id: winwincode_domain::DeliveryId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "deliveryTaskId")]
    pub delivery_task_id: Option<winwincode_domain::DeliveryTaskId>,
    #[serde(rename = "kind")]
    pub kind: DeliveryStageExecutionScopeKind,
    #[serde(rename = "productSessionId")]
    pub product_session_id: winwincode_domain::ProductSessionId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "reworkAuthorization")]
    pub rework_authorization: Option<DeliveryReworkAuthorizationScope>,
    #[serde(rename = "stageRunId")]
    pub stage_run_id: winwincode_domain::StageRunId,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeliveryStageInput {
    #[serde(rename = "acceptanceCriteria")]
    pub acceptance_criteria: Vec<DeliveryStageAcceptanceCriterionInput>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "candidateRef")]
    pub candidate_ref: Option<String>,
    #[serde(rename = "constraints")]
    pub constraints: Vec<String>,
    #[serde(rename = "deliverySpecId")]
    pub delivery_spec_id: String,
    #[serde(rename = "deliverySpecRevision")]
    pub delivery_spec_revision: i64,
    #[serde(rename = "goal")]
    pub goal: String,
    #[serde(rename = "outOfScope")]
    pub out_of_scope: Vec<String>,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "scope")]
    pub scope: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "task")]
    pub task: Option<DeliveryStageTaskInput>,
    #[serde(rename = "title")]
    pub title: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DeliveryStageTaskInput {
    #[serde(rename = "acceptanceCriterionIds")]
    pub acceptance_criterion_ids: Vec<String>,
    #[serde(rename = "goal")]
    pub goal: String,
    #[serde(rename = "taskId")]
    pub task_id: winwincode_domain::DeliveryTaskId,
    #[serde(rename = "title")]
    pub title: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EncodedPayload {
    #[serde(rename = "contentType")]
    pub content_type: String,
    #[serde(rename = "dataBase64")]
    pub data_base64: String,
    #[serde(rename = "payloadDigest")]
    pub payload_digest: winwincode_domain::Sha256Digest,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ExecutionEventCategory {
    #[serde(rename = "lifecycle")]
    Lifecycle,
    #[serde(rename = "activity")]
    Activity,
    #[serde(rename = "command")]
    Command,
    #[serde(rename = "test")]
    Test,
    #[serde(rename = "diff")]
    Diff,
    #[serde(rename = "usage")]
    Usage,
    #[serde(rename = "attention")]
    Attention,
    #[serde(rename = "diagnostic")]
    Diagnostic,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExecutionEventRecord {
    #[serde(rename = "category")]
    pub category: ExecutionEventCategory,
    #[serde(rename = "eventId")]
    pub event_id: winwincode_domain::ExecutionEventId,
    #[serde(rename = "occurredAt")]
    pub occurred_at: winwincode_domain::Instant,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "payload")]
    pub payload: Option<EncodedPayload>,
    #[serde(rename = "sequence")]
    pub sequence: winwincode_domain::ExecutionSequence,
    #[serde(rename = "summary")]
    pub summary: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExecutionJob {
    #[serde(rename = "attempt")]
    pub attempt: i64,
    #[serde(rename = "executionProfile")]
    pub execution_profile: String,
    #[serde(rename = "goal")]
    pub goal: String,
    #[serde(rename = "jobId")]
    pub job_id: winwincode_domain::ExecutionJobId,
    #[serde(rename = "limits")]
    pub limits: ExecutionLimits,
    #[serde(rename = "payloadDigest")]
    pub payload_digest: winwincode_domain::Sha256Digest,
    #[serde(rename = "scope")]
    pub scope: ExecutionScope,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "stageInput")]
    pub stage_input: Option<DeliveryStageInput>,
    #[serde(rename = "workspace")]
    pub workspace: ExecutionWorkspace,
}

/// Control Plane seal for one exact predecessor-to-successor Job replacement. The predecessor lease and optional bound session also authorize exact continuation of an already durable Artifact stream; they never authorize a new stream.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExecutionJobReplacementAuthority {
    #[serde(rename = "createdAt")]
    pub created_at: winwincode_domain::Instant,
    #[serde(rename = "logicalJobDigest")]
    pub logical_job_digest: winwincode_domain::Sha256Digest,
    #[serde(rename = "predecessorLease")]
    pub predecessor_lease: ExecutionLeaseStamp,
    /// The exact slot-bound predecessor WorkerSession and CodexThread. Null means no predecessor slot-bound runtime exists; the predecessor dispatch may have been accepted, but null authorizes neither dirty-workspace reuse nor continuation of an old runtime or Artifact stream.
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "predecessorSessionIdentity")]
    pub predecessor_session_identity: Option<winwincode_domain::SessionIdentity>,
    #[serde(rename = "receiptDigest")]
    pub receipt_digest: winwincode_domain::Sha256Digest,
    #[serde(rename = "receiptId")]
    pub receipt_id: winwincode_domain::RequestId,
    #[serde(rename = "scope")]
    pub scope: ExecutionScope,
    #[serde(rename = "successorLease")]
    pub successor_lease: ExecutionLeaseStamp,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExecutionLeaseStamp {
    #[serde(rename = "attempt")]
    pub attempt: i64,
    #[serde(rename = "expiresAt")]
    pub expires_at: winwincode_domain::Instant,
    #[serde(rename = "fencingToken")]
    pub fencing_token: winwincode_domain::FencingToken,
    #[serde(rename = "issuedAt")]
    pub issued_at: winwincode_domain::Instant,
    #[serde(rename = "jobId")]
    pub job_id: winwincode_domain::ExecutionJobId,
    #[serde(rename = "leaseId")]
    pub lease_id: winwincode_domain::LeaseId,
    #[serde(rename = "workerId")]
    pub worker_id: winwincode_domain::WorkerId,
    #[serde(rename = "workerInstanceId")]
    pub worker_instance_id: winwincode_domain::WorkerInstanceId,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExecutionLimits {
    #[serde(rename = "deadlineAt")]
    pub deadline_at: winwincode_domain::Instant,
    #[serde(rename = "maxArtifactBytes")]
    pub max_artifact_bytes: i64,
    #[serde(rename = "maxRuntimeSeconds")]
    pub max_runtime_seconds: i64,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExecutionOutcome {
    #[serde(rename = "artifacts")]
    pub artifacts: Vec<ArtifactReference>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "codexThreadId")]
    pub codex_thread_id: Option<winwincode_domain::CodexThreadId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "error")]
    pub error: Option<ExecutionPortError>,
    #[serde(rename = "finishedAt")]
    pub finished_at: winwincode_domain::Instant,
    #[serde(rename = "lastEventSequence")]
    pub last_event_sequence: winwincode_domain::ExecutionAckSequence,
    #[serde(rename = "status")]
    pub status: ExecutionOutcomeStatus,
    #[serde(rename = "summary")]
    pub summary: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "usage")]
    pub usage: Option<ExecutionOutcomeUsage>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ExecutionOutcomeStatus {
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "infrastructure_error")]
    InfrastructureError,
    #[serde(rename = "succeeded")]
    Succeeded,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExecutionOutcomeUsage {
    #[serde(rename = "costMicrounits")]
    pub cost_microunits: i64,
    #[serde(rename = "runtimeMillis")]
    pub runtime_millis: i64,
    #[serde(rename = "tokens")]
    pub tokens: i64,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExecutionPortError {
    #[serde(rename = "code")]
    pub code: ExecutionPortErrorCode,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "retryable")]
    pub retryable: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ExecutionPortErrorCode {
    #[serde(rename = "PROTOCOL_VERSION_UNSUPPORTED")]
    ProtocolVersionUnsupported,
    #[serde(rename = "WORKER_NOT_REGISTERED")]
    WorkerNotRegistered,
    #[serde(rename = "CAPABILITY_MISMATCH")]
    CapabilityMismatch,
    #[serde(rename = "JOB_DISPATCH_CONFLICT")]
    JobDispatchConflict,
    #[serde(rename = "LEASE_EXPIRED")]
    LeaseExpired,
    #[serde(rename = "STALE_FENCING_TOKEN")]
    StaleFencingToken,
    #[serde(rename = "WORKER_INSTANCE_CHANGED")]
    WorkerInstanceChanged,
    #[serde(rename = "SEQUENCE_GAP")]
    SequenceGap,
    #[serde(rename = "MESSAGE_CONFLICT")]
    MessageConflict,
    #[serde(rename = "ARTIFACT_DIGEST_MISMATCH")]
    ArtifactDigestMismatch,
    #[serde(rename = "MODEL_STREAM_FAILED")]
    ModelStreamFailed,
    #[serde(rename = "INPUT_CLOSED")]
    InputClosed,
    #[serde(rename = "APPROVAL_DENIED")]
    ApprovalDenied,
    #[serde(rename = "CANCELLED")]
    Cancelled,
    #[serde(rename = "EXECUTION_FAILED")]
    ExecutionFailed,
    #[serde(rename = "INFRASTRUCTURE_ERROR")]
    InfrastructureError,
}

/// The single versioned message union shared by local and remote ExecutionPort adapters.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(untagged)]
pub enum ExecutionPortMessage {
    WorkerRegisterMessage(WorkerRegisterMessage),
    WorkerRegistrationResultMessage(WorkerRegistrationResultMessage),
    WorkerCapabilitiesMessage(WorkerCapabilitiesMessage),
    WorkerHeartbeatMessage(WorkerHeartbeatMessage),
    WorkerHeartbeatAckMessage(WorkerHeartbeatAckMessage),
    JobDispatchMessage(JobDispatchMessage),
    JobDispatchResultMessage(JobDispatchResultMessage),
    SessionBindingMessage(SessionBindingMessage),
    LeaseRenewMessage(LeaseRenewMessage),
    RuntimeEventMessage(RuntimeEventMessage),
    RuntimeAckMessage(RuntimeAckMessage),
    RuntimeReplayRequestMessage(RuntimeReplayRequestMessage),
    ArtifactOpenMessage(ArtifactOpenMessage),
    ArtifactChunkMessage(ArtifactChunkMessage),
    ArtifactAckMessage(ArtifactAckMessage),
    ModelOpenMessage(ModelOpenMessage),
    ModelChunkMessage(ModelChunkMessage),
    ModelAckMessage(ModelAckMessage),
    InputRequestMessage(InputRequestMessage),
    InputResponseMessage(InputResponseMessage),
    ApprovalRequestMessage(ApprovalRequestMessage),
    ApprovalDecisionMessage(ApprovalDecisionMessage),
    JobCancelMessage(JobCancelMessage),
    JobCancelAckMessage(JobCancelAckMessage),
    JobOutcomeMessage(JobOutcomeMessage),
    JobOutcomeAckMessage(JobOutcomeAckMessage),
    ActionEnforcementRequestMessage(ActionEnforcementRequestMessage),
    ActionEnforcementReceiptMessage(ActionEnforcementReceiptMessage),
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(untagged)]
pub enum ExecutionScope {
    ProductSessionExecutionScope(ProductSessionExecutionScope),
    DeliveryStageExecutionScope(DeliveryStageExecutionScope),
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ExecutionWorkspaceWriteMode {
    #[serde(rename = "read-only")]
    ReadOnly,
    #[serde(rename = "candidate")]
    Candidate,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExecutionWorkspace {
    #[serde(rename = "checkoutRevision")]
    pub checkout_revision: String,
    #[serde(rename = "repositoryId")]
    pub repository_id: winwincode_domain::RepositoryId,
    #[serde(rename = "writeMode")]
    pub write_mode: ExecutionWorkspaceWriteMode,
}

/// Requests one typed user input through the Control Plane product session.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum InputRequestMessageKind {
    #[serde(rename = "input.request")]
    InputRequest,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct InputRequestMessage {
    #[serde(rename = "allowEmpty")]
    pub allow_empty: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "choices")]
    pub choices: Option<Vec<InteractiveInputChoice>>,
    #[serde(rename = "expiresAt")]
    pub expires_at: winwincode_domain::Instant,
    #[serde(rename = "inputRequestId")]
    pub input_request_id: winwincode_domain::InputRequestId,
    #[serde(rename = "kind")]
    pub kind: InputRequestMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "mode")]
    pub mode: winwincode_domain::InteractiveInputMode,
    #[serde(rename = "prompt")]
    pub prompt: String,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Returns a typed input result without exposing product-session storage.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum InputResponseMessageKind {
    #[serde(rename = "input.response")]
    InputResponse,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum InputResponseMessageStatus {
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "provided")]
    Provided,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct InputResponseMessage {
    #[serde(rename = "inputRequestId")]
    pub input_request_id: winwincode_domain::InputRequestId,
    #[serde(rename = "kind")]
    pub kind: InputResponseMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "respondedAt")]
    pub responded_at: winwincode_domain::Instant,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "status")]
    pub status: InputResponseMessageStatus,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "value")]
    pub value: Option<winwincode_domain::InteractiveInputValue>,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// One interactive option. id is the stable UI/business identity; value is the canonical answer submitted to the Worker.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct InteractiveInputChoice {
    #[serde(rename = "id")]
    pub id: winwincode_domain::InteractiveInputChoiceId,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "value")]
    pub value: String,
}

/// Acknowledges cancellation without declaring a Delivery result.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum JobCancelAckMessageKind {
    #[serde(rename = "job.cancel_ack")]
    JobCancelAck,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum JobCancelAckMessageStatus {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "already_cancelling")]
    AlreadyCancelling,
    #[serde(rename = "already_terminal")]
    AlreadyTerminal,
    #[serde(rename = "rejected_expired_lease")]
    RejectedExpiredLease,
    #[serde(rename = "rejected_stale_fencing_token")]
    RejectedStaleFencingToken,
    #[serde(rename = "rejected_worker_instance")]
    RejectedWorkerInstance,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JobCancelAckMessage {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "error")]
    pub error: Option<ExecutionPortError>,
    #[serde(rename = "kind")]
    pub kind: JobCancelAckMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "status")]
    pub status: JobCancelAckMessageStatus,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Requests cooperative cancellation for the currently fenced attempt.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum JobCancelMessageKind {
    #[serde(rename = "job.cancel")]
    JobCancel,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum JobCancelMessageReason {
    #[serde(rename = "deadline")]
    Deadline,
    #[serde(rename = "policy")]
    Policy,
    #[serde(rename = "shutdown")]
    Shutdown,
    #[serde(rename = "superseded")]
    Superseded,
    #[serde(rename = "user_requested")]
    UserRequested,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JobCancelMessage {
    #[serde(rename = "kind")]
    pub kind: JobCancelMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "reason")]
    pub reason: JobCancelMessageReason,
    #[serde(rename = "requestedAt")]
    pub requested_at: winwincode_domain::Instant,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Dispatches one immutable job payload under one attempt and lease.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum JobDispatchMessageKind {
    #[serde(rename = "job.dispatch")]
    JobDispatch,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JobDispatchMessage {
    #[serde(rename = "job")]
    pub job: ExecutionJob,
    #[serde(rename = "kind")]
    pub kind: JobDispatchMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "replacementAuthority")]
    pub replacement_authority: Option<ExecutionJobReplacementAuthority>,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
}

/// Returns the idempotent result of accepting or rejecting a job dispatch.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum JobDispatchResultMessageKind {
    #[serde(rename = "job.dispatch_result")]
    JobDispatchResult,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum JobDispatchResultMessageStatus {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "duplicate")]
    Duplicate,
    #[serde(rename = "conflict")]
    Conflict,
    #[serde(rename = "rejected_capacity")]
    RejectedCapacity,
    #[serde(rename = "rejected_capability")]
    RejectedCapability,
    #[serde(rename = "rejected_expired_lease")]
    RejectedExpiredLease,
    #[serde(rename = "rejected_stale_fencing_token")]
    RejectedStaleFencingToken,
    #[serde(rename = "rejected_worker_instance")]
    RejectedWorkerInstance,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JobDispatchResultMessage {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "error")]
    pub error: Option<ExecutionPortError>,
    #[serde(rename = "jobId")]
    pub job_id: winwincode_domain::ExecutionJobId,
    #[serde(rename = "kind")]
    pub kind: JobDispatchResultMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "payloadDigest")]
    pub payload_digest: winwincode_domain::Sha256Digest,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "status")]
    pub status: JobDispatchResultMessageStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: Option<winwincode_domain::WorkerSessionId>,
}

/// Accepts or rejects one lease-fenced execution outcome idempotently.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum JobOutcomeAckMessageKind {
    #[serde(rename = "job.outcome_ack")]
    JobOutcomeAck,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum JobOutcomeAckMessageStatus {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "duplicate")]
    Duplicate,
    #[serde(rename = "rejected_conflict")]
    RejectedConflict,
    #[serde(rename = "rejected_expired_lease")]
    RejectedExpiredLease,
    #[serde(rename = "rejected_stale_fencing_token")]
    RejectedStaleFencingToken,
    #[serde(rename = "rejected_worker_instance")]
    RejectedWorkerInstance,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JobOutcomeAckMessage {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "error")]
    pub error: Option<ExecutionPortError>,
    #[serde(rename = "kind")]
    pub kind: JobOutcomeAckMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "status")]
    pub status: JobOutcomeAckMessageStatus,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Reports an execution outcome; Control Plane alone derives canonical Delivery state and verdicts.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum JobOutcomeMessageKind {
    #[serde(rename = "job.outcome")]
    JobOutcome,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JobOutcomeMessage {
    #[serde(rename = "kind")]
    pub kind: JobOutcomeMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "outcome")]
    pub outcome: ExecutionOutcome,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Extends one lease for the same Worker instance, attempt, and fencing token.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum LeaseRenewMessageKind {
    #[serde(rename = "lease.renew")]
    LeaseRenew,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LeaseRenewMessage {
    #[serde(rename = "kind")]
    pub kind: LeaseRenewMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "priorExpiresAt")]
    pub prior_expires_at: winwincode_domain::Instant,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum LeaseWriteStatus {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "duplicate")]
    Duplicate,
    #[serde(rename = "gap")]
    Gap,
    #[serde(rename = "rejected_conflict")]
    RejectedConflict,
    #[serde(rename = "rejected_expired_lease")]
    RejectedExpiredLease,
    #[serde(rename = "rejected_stale_fencing_token")]
    RejectedStaleFencingToken,
    #[serde(rename = "rejected_worker_instance")]
    RejectedWorkerInstance,
}

/// Acknowledges model chunks and requests replay after a stream interruption.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ModelAckMessageKind {
    #[serde(rename = "model.ack")]
    ModelAck,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelAckMessage {
    #[serde(rename = "ackSequence")]
    pub ack_sequence: winwincode_domain::ExecutionAckSequence,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "error")]
    pub error: Option<ExecutionPortError>,
    #[serde(rename = "kind")]
    pub kind: ModelAckMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "modelExchangeId")]
    pub model_exchange_id: winwincode_domain::ModelExchangeId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "replayFromSequence")]
    pub replay_from_sequence: Option<winwincode_domain::ExecutionSequence>,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "status")]
    pub status: LeaseWriteStatus,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Streams one opaque provider-neutral model response chunk.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ModelChunkMessageKind {
    #[serde(rename = "model.chunk")]
    ModelChunk,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelChunkMessage {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "error")]
    pub error: Option<ExecutionPortError>,
    #[serde(rename = "isFinal")]
    pub is_final: bool,
    #[serde(rename = "kind")]
    pub kind: ModelChunkMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "modelExchangeId")]
    pub model_exchange_id: winwincode_domain::ModelExchangeId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "payload")]
    pub payload: Option<EncodedPayload>,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sequence")]
    pub sequence: winwincode_domain::ExecutionSequence,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelGatewayRoute {
    #[serde(rename = "capability")]
    pub capability: String,
    #[serde(rename = "route")]
    pub route: String,
}

/// Opens one provider-neutral model exchange through the Control Plane gateway.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ModelOpenMessageKind {
    #[serde(rename = "model.open")]
    ModelOpen,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelOpenMessage {
    #[serde(rename = "kind")]
    pub kind: ModelOpenMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "modelExchangeId")]
    pub model_exchange_id: winwincode_domain::ModelExchangeId,
    #[serde(rename = "request")]
    pub request: EncodedPayload,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "route")]
    pub route: ModelGatewayRoute,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ProductSessionExecutionScopeKind {
    #[serde(rename = "product-session")]
    ProductSession,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProductSessionExecutionScope {
    #[serde(rename = "kind")]
    pub kind: ProductSessionExecutionScopeKind,
    #[serde(rename = "productSessionId")]
    pub product_session_id: winwincode_domain::ProductSessionId,
}

/// Acknowledges the highest contiguous runtime event and requests a gap replay when needed.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum RuntimeAckMessageKind {
    #[serde(rename = "runtime.ack")]
    RuntimeAck,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RuntimeAckMessage {
    #[serde(rename = "ackSequence")]
    pub ack_sequence: winwincode_domain::ExecutionAckSequence,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "error")]
    pub error: Option<ExecutionPortError>,
    #[serde(rename = "kind")]
    pub kind: RuntimeAckMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "replayFromSequence")]
    pub replay_from_sequence: Option<winwincode_domain::ExecutionSequence>,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "status")]
    pub status: LeaseWriteStatus,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Publishes one ordered, replayable, provider-neutral runtime fact.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum RuntimeEventMessageKind {
    #[serde(rename = "runtime.event")]
    RuntimeEvent,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RuntimeEventMessage {
    #[serde(rename = "codexThreadId")]
    pub codex_thread_id: winwincode_domain::CodexThreadId,
    #[serde(rename = "event")]
    pub event: ExecutionEventRecord,
    #[serde(rename = "kind")]
    pub kind: RuntimeEventMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Requests original runtime events strictly after the acknowledged sequence.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum RuntimeReplayRequestMessageKind {
    #[serde(rename = "runtime.replay_request")]
    RuntimeReplayRequest,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RuntimeReplayRequestMessage {
    #[serde(rename = "afterSequence")]
    pub after_sequence: winwincode_domain::ExecutionAckSequence,
    #[serde(rename = "kind")]
    pub kind: RuntimeReplayRequestMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "maxEvents")]
    pub max_events: i64,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Authoritative WorkerSession-to-CodexThread binding for one exact active Job lease. Delivery-stage bindings carry the exact StageRun; ProductSession Chat bindings omit it.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum SessionBindingMessageKind {
    #[serde(rename = "session.binding")]
    SessionBinding,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SessionBindingMessage {
    #[serde(rename = "attempt")]
    pub attempt: i64,
    #[serde(rename = "boundAt")]
    pub bound_at: winwincode_domain::Instant,
    #[serde(rename = "codexThreadId")]
    pub codex_thread_id: winwincode_domain::CodexThreadId,
    #[serde(rename = "fencingToken")]
    pub fencing_token: winwincode_domain::FencingToken,
    #[serde(rename = "kind")]
    pub kind: SessionBindingMessageKind,
    #[serde(rename = "lease")]
    pub lease: ExecutionLeaseStamp,
    #[serde(rename = "leaseId")]
    pub lease_id: winwincode_domain::LeaseId,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "productSessionId")]
    pub product_session_id: winwincode_domain::ProductSessionId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: winwincode_domain::SessionIdentity,
    #[serde(rename = "sourceIdentity")]
    pub source_identity: winwincode_domain::SessionBindingSourceIdentity,
    /// Exact Delivery StageRun identity. ProductSession Chat bindings omit this field.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "stageRunId")]
    pub stage_run_id: Option<winwincode_domain::StageRunId>,
    #[serde(rename = "workerId")]
    pub worker_id: winwincode_domain::WorkerId,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: winwincode_domain::WorkerSessionId,
}

/// Replaces the registered capability snapshot for the current Worker instance.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum WorkerCapabilitiesMessageKind {
    #[serde(rename = "worker.capabilities")]
    WorkerCapabilities,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerCapabilitiesMessage {
    #[serde(rename = "capabilities")]
    pub capabilities: WorkerCapabilitySet,
    #[serde(rename = "kind")]
    pub kind: WorkerCapabilitiesMessageKind,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "observedAt")]
    pub observed_at: winwincode_domain::Instant,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "workerId")]
    pub worker_id: winwincode_domain::WorkerId,
    #[serde(rename = "workerInstanceId")]
    pub worker_instance_id: winwincode_domain::WorkerInstanceId,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum WorkerCapabilityFeature {
    #[serde(rename = "artifact_stream")]
    ArtifactStream,
    #[serde(rename = "approval")]
    Approval,
    #[serde(rename = "git")]
    Git,
    #[serde(rename = "interactive_input")]
    InteractiveInput,
    #[serde(rename = "mcp")]
    Mcp,
    #[serde(rename = "model_proxy")]
    ModelProxy,
    #[serde(rename = "sandbox")]
    Sandbox,
    #[serde(rename = "shell")]
    Shell,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum WorkerCapabilitySetPlatform {
    #[serde(rename = "aarch64-apple-darwin")]
    Aarch64AppleDarwin,
    #[serde(rename = "x86_64-apple-darwin")]
    X8664AppleDarwin,
    #[serde(rename = "aarch64-unknown-linux-gnu")]
    Aarch64UnknownLinuxGnu,
    #[serde(rename = "x86_64-unknown-linux-gnu")]
    X8664UnknownLinuxGnu,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerCapabilitySet {
    #[serde(rename = "capabilityDigest")]
    pub capability_digest: winwincode_domain::Sha256Digest,
    #[serde(rename = "features")]
    pub features: Vec<WorkerCapabilityFeature>,
    #[serde(rename = "maxConcurrentJobs")]
    pub max_concurrent_jobs: i64,
    #[serde(rename = "platform")]
    pub platform: WorkerCapabilitySetPlatform,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerCapacity {
    #[serde(rename = "availableSlots")]
    pub available_slots: i64,
    #[serde(rename = "runningJobs")]
    pub running_jobs: i64,
}

/// Acknowledges exactly one heartbeat without dispatching jobs as a side effect.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum WorkerHeartbeatAckMessageKind {
    #[serde(rename = "worker.heartbeat_ack")]
    WorkerHeartbeatAck,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum WorkerHeartbeatAckMessageStatus {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "duplicate")]
    Duplicate,
    #[serde(rename = "rejected_worker_instance")]
    RejectedWorkerInstance,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerHeartbeatAckMessage {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "error")]
    pub error: Option<ExecutionPortError>,
    #[serde(rename = "heartbeatSequence")]
    pub heartbeat_sequence: winwincode_domain::ExecutionSequence,
    #[serde(rename = "kind")]
    pub kind: WorkerHeartbeatAckMessageKind,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "nextHeartbeatWithinMs")]
    pub next_heartbeat_within_ms: i64,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "serverTime")]
    pub server_time: winwincode_domain::Instant,
    #[serde(rename = "status")]
    pub status: WorkerHeartbeatAckMessageStatus,
    #[serde(rename = "workerId")]
    pub worker_id: winwincode_domain::WorkerId,
    #[serde(rename = "workerInstanceId")]
    pub worker_instance_id: winwincode_domain::WorkerInstanceId,
}

/// Reports liveness, capacity, and lease progress for one Worker instance.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum WorkerHeartbeatMessageKind {
    #[serde(rename = "worker.heartbeat")]
    WorkerHeartbeat,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerHeartbeatMessage {
    #[serde(rename = "activeLeases")]
    pub active_leases: Vec<ActiveLeaseSummary>,
    #[serde(rename = "capacity")]
    pub capacity: WorkerCapacity,
    #[serde(rename = "heartbeatSequence")]
    pub heartbeat_sequence: winwincode_domain::ExecutionSequence,
    #[serde(rename = "kind")]
    pub kind: WorkerHeartbeatMessageKind,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "observedAt")]
    pub observed_at: winwincode_domain::Instant,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "workerId")]
    pub worker_id: winwincode_domain::WorkerId,
    #[serde(rename = "workerInstanceId")]
    pub worker_instance_id: winwincode_domain::WorkerInstanceId,
}

/// Registers one stable Worker identity and one process-boot identity.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum WorkerRegisterMessageKind {
    #[serde(rename = "worker.register")]
    WorkerRegister,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerRegisterMessage {
    #[serde(rename = "capabilities")]
    pub capabilities: WorkerCapabilitySet,
    #[serde(rename = "kind")]
    pub kind: WorkerRegisterMessageKind,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "startedAt")]
    pub started_at: winwincode_domain::Instant,
    #[serde(rename = "workerId")]
    pub worker_id: winwincode_domain::WorkerId,
    #[serde(rename = "workerInstanceId")]
    pub worker_instance_id: winwincode_domain::WorkerInstanceId,
}

/// Returns the idempotent registration result and restart lease recovery rule.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum WorkerRegistrationResultMessageKind {
    #[serde(rename = "worker.registration_result")]
    WorkerRegistrationResult,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum WorkerRegistrationResultMessageStatus {
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "duplicate")]
    Duplicate,
    #[serde(rename = "rejected")]
    Rejected,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum WorkerRegistrationResultMessageLeaseRecovery {
    #[serde(rename = "no_active_leases")]
    NoActiveLeases,
    #[serde(rename = "reacquire_required")]
    ReacquireRequired,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkerRegistrationResultMessage {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "error")]
    pub error: Option<ExecutionPortError>,
    #[serde(rename = "heartbeatIntervalMs")]
    pub heartbeat_interval_ms: i64,
    #[serde(rename = "kind")]
    pub kind: WorkerRegistrationResultMessageKind,
    #[serde(rename = "leaseRecovery")]
    pub lease_recovery: WorkerRegistrationResultMessageLeaseRecovery,
    #[serde(rename = "messageId")]
    pub message_id: winwincode_domain::ExecutionMessageId,
    #[serde(rename = "requestId")]
    pub request_id: winwincode_domain::RequestId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: winwincode_domain::SchemaVersion,
    #[serde(rename = "sentAt")]
    pub sent_at: winwincode_domain::Instant,
    #[serde(rename = "serverTime")]
    pub server_time: winwincode_domain::Instant,
    #[serde(rename = "status")]
    pub status: WorkerRegistrationResultMessageStatus,
    #[serde(rename = "workerId")]
    pub worker_id: winwincode_domain::WorkerId,
    #[serde(rename = "workerInstanceId")]
    pub worker_instance_id: winwincode_domain::WorkerInstanceId,
}
