// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/build/generate-contracts.mjs. Do not edit.

export type DeviceConfigurationEnvelope = {
  readonly "ciphertext": string
  readonly "clientNodeId": string
  readonly "expectedRevision": number
  readonly "nonce": string
  readonly "publicKey": string
  readonly "requestId": string
}

export type DeviceExtensionMcp = {
  readonly "connectionStatus": DeviceExtensionMcpConnectionStatus
  readonly "digest": string
  readonly "enabled": boolean
  readonly "id": string
  readonly "toolNames": ReadonlyArray<string>
  readonly "transport": DeviceExtensionMcpTransport
}

export enum DeviceExtensionMcpConnectionStatus {
  Untested = "untested",
  Ready = "ready",
  Failed = "failed",
}

export enum DeviceExtensionMcpTransport {
  Stdio = "stdio",
  StreamableHttp = "streamable_http",
}

export enum DeviceExtensionOutcome {
  Saved = "saved",
  Deleted = "deleted",
  Tested = "tested",
  InvalidRequest = "invalid_request",
  RevisionConflict = "revision_conflict",
  ConnectionFailed = "connection_failed",
  Interrupted = "interrupted",
}

export type DeviceExtensionReceipt = {
  readonly "outcome": DeviceExtensionOutcome
  readonly "requestId": string
  readonly "revision": number
}

export type DeviceExtensionReport = {
  readonly "receipt": DeviceExtensionReceipt | null
  readonly "snapshot": DeviceExtensionSnapshot
}

export type DeviceExtensionSkill = {
  readonly "description": string
  readonly "digest": string
  readonly "enabled": boolean
  readonly "fileCount": number
  readonly "id": string
  readonly "name": string
  readonly "source": string
}

export type DeviceExtensionSnapshot = {
  readonly "clientNodeId": string
  readonly "encryptionPublicKey": string
  readonly "mcpServers": ReadonlyArray<DeviceExtensionMcp>
  readonly "revision": number
  readonly "skills": ReadonlyArray<DeviceExtensionSkill>
}

export type DeviceProviderConfig = {
  readonly "displayName": string
  readonly "enabled": boolean
  readonly "endpoint": string
  readonly "modelIds": ReadonlyArray<string>
  readonly "protocol": DeviceProviderProtocol
  readonly "providerId": string
}

export type DeviceProviderOpenCodeAccount = {
  readonly "accountRef": OpenCodeAccountId
  readonly "credentialVersion": number
  readonly "email": string
  readonly "issuer": "https://opencode.ai/console"
  readonly "state": DeviceProviderOpenCodeAccountState
  readonly "subject": string
  readonly "usage"?: DeviceProviderOpenCodeUsage
}

export enum DeviceProviderOpenCodeAccountState {
  Authorized = "authorized",
  RefreshInFlight = "refresh_in_flight",
  ReauthorizationRequired = "reauthorization_required",
  LoggedOut = "logged_out",
}

export type DeviceProviderOpenCodeCommand = {
  readonly "accountRef"?: OpenCodeAccountId
  readonly "displayName"?: string
  readonly "loginId"?: OpenCodeLoginId
  readonly "modelId"?: string
  readonly "operation": DeviceProviderOpenCodeOperation
  readonly "organizationId"?: string
  readonly "providerId"?: string
}

export type DeviceProviderOpenCodeConnection = {
  readonly "accountRef": OpenCodeAccountId
  readonly "organizationId": string
  readonly "organizationName": string
}

export type DeviceProviderOpenCodeLogin = {
  readonly "accountRef"?: OpenCodeAccountId
  readonly "expiresAtMs": number
  readonly "loginId": OpenCodeLoginId
  readonly "organizations": ReadonlyArray<DeviceProviderOpenCodeOrganization>
  readonly "pollAfterMs": number
  readonly "state": DeviceProviderOpenCodeLoginState
  readonly "userCode"?: string
  readonly "verificationUri"?: string
}

export enum DeviceProviderOpenCodeLoginState {
  Pending = "pending",
  Authorized = "authorized",
  Denied = "denied",
  Expired = "expired",
  Cancelled = "cancelled",
  Failed = "failed",
  Completed = "completed",
}

export enum DeviceProviderOpenCodeOperation {
  BeginOpencodeLogin = "begin_opencode_login",
  PollOpencodeLogin = "poll_opencode_login",
  CancelOpencodeLogin = "cancel_opencode_login",
  ConnectOpencode = "connect_opencode",
  LogoutOpencode = "logout_opencode",
  OpencodeUsage = "opencode_usage",
  SetDefaultProvider = "set_default_provider",
}

export type DeviceProviderOpenCodeOrganization = {
  readonly "id": string
  readonly "name": string
}

export type DeviceProviderOpenCodeSessionBinding = {
  readonly "accountRef": OpenCodeAccountId
  readonly "conversationId": string
  readonly "organizationId": string
  readonly "productSessionId": ProductSessionId
  readonly "providerId": string
}

export type DeviceProviderOpenCodeUsage = {
  readonly "monthly": DeviceProviderOpenCodeUsageWindow
  readonly "organizationId": string
  readonly "rolling": DeviceProviderOpenCodeUsageWindow
  readonly "updatedAtMs": number
  readonly "weekly": DeviceProviderOpenCodeUsageWindow
}

export type DeviceProviderOpenCodeUsageWindow = {
  readonly "percent": number
  readonly "resetsAt": string
  readonly "status": string
}

export enum DeviceProviderOutcome {
  Saved = "saved",
  Deleted = "deleted",
  Tested = "tested",
  InvalidRequest = "invalid_request",
  RevisionConflict = "revision_conflict",
  ProviderUnavailable = "provider_unavailable",
  Interrupted = "interrupted",
}

export type DeviceProviderProjection = {
  readonly "config": DeviceProviderConfig
  readonly "credentialConfigured": boolean
  readonly "openCode"?: DeviceProviderOpenCodeConnection
}

export enum DeviceProviderProtocol {
  AnthropicMessages = "anthropic_messages",
  OpenaiChatCompletions = "openai_chat_completions",
  Canonical = "canonical",
}

export type DeviceProviderReceipt = {
  readonly "outcome": DeviceProviderOutcome
  readonly "requestId": string
  readonly "revision": number
}

export type DeviceProviderReport = {
  readonly "receipt": DeviceProviderReceipt | null
  readonly "snapshot": DeviceProviderSnapshot
}

export type DeviceProviderSnapshot = {
  readonly "clientNodeId": string
  readonly "defaultProviderId"?: string
  readonly "encryptionPublicKey": string
  readonly "openCodeAccounts"?: ReadonlyArray<DeviceProviderOpenCodeAccount>
  readonly "openCodeLogins"?: ReadonlyArray<DeviceProviderOpenCodeLogin>
  readonly "providers": ReadonlyArray<DeviceProviderProjection>
  readonly "revision": number
}

/** Device-local OAuth account identity. It refers to one verified issuer and upstream subject. */
export type OpenCodeAccountId = string & { readonly __brand: "OpenCodeAccountId" }

/** Device-owned, bounded OpenCode device authorization operation. */
export type OpenCodeLoginId = string & { readonly __brand: "OpenCodeLoginId" }

export type ProductSessionId = string & { readonly __brand: "ProductSessionId" }
