// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-contracts.mjs. Do not edit.

export type DeviceConfigurationEnvelope = {
  readonly "ciphertext": string
  readonly "clientNodeId": string
  readonly "expectedRevision": number
  readonly "nonce": string
  readonly "publicKey": string
  readonly "requestId": string
}

export type DeviceExtensionMcp = {
  readonly "connectionStatus": DeviceExtensionMcpConnectionStatus
  readonly "digest": string
  readonly "enabled": boolean
  readonly "id": string
  readonly "toolNames": ReadonlyArray<string>
  readonly "transport": DeviceExtensionMcpTransport
}

export enum DeviceExtensionMcpConnectionStatus {
  Untested = "untested",
  Ready = "ready",
  Failed = "failed",
}

export enum DeviceExtensionMcpTransport {
  Stdio = "stdio",
  StreamableHttp = "streamable_http",
}

export enum DeviceExtensionOutcome {
  Saved = "saved",
  Deleted = "deleted",
  Tested = "tested",
  InvalidRequest = "invalid_request",
  RevisionConflict = "revision_conflict",
  ConnectionFailed = "connection_failed",
  Interrupted = "interrupted",
}

export type DeviceExtensionReceipt = {
  readonly "outcome": DeviceExtensionOutcome
  readonly "requestId": string
  readonly "revision": number
}

export type DeviceExtensionReport = {
  readonly "receipt": DeviceExtensionReceipt | null
  readonly "snapshot": DeviceExtensionSnapshot
}

export type DeviceExtensionSkill = {
  readonly "description": string
  readonly "digest": string
  readonly "enabled": boolean
  readonly "fileCount": number
  readonly "id": string
  readonly "name": string
  readonly "source": string
}

export type DeviceExtensionSnapshot = {
  readonly "clientNodeId": string
  readonly "encryptionPublicKey": string
  readonly "mcpServers": ReadonlyArray<DeviceExtensionMcp>
  readonly "revision": number
  readonly "skills": ReadonlyArray<DeviceExtensionSkill>
}

export type DeviceProviderConfig = {
  readonly "displayName": string
  readonly "enabled": boolean
  readonly "endpoint": string
  readonly "modelIds": ReadonlyArray<string>
  readonly "protocol": DeviceProviderProtocol
  readonly "providerId": string
}

export enum DeviceProviderOutcome {
  Saved = "saved",
  Deleted = "deleted",
  Tested = "tested",
  InvalidRequest = "invalid_request",
  RevisionConflict = "revision_conflict",
  ProviderUnavailable = "provider_unavailable",
  Interrupted = "interrupted",
}

export type DeviceProviderProjection = {
  readonly "config": DeviceProviderConfig
  readonly "credentialConfigured": boolean
}

export enum DeviceProviderProtocol {
  AnthropicMessages = "anthropic_messages",
  Canonical = "canonical",
}

export type DeviceProviderReceipt = {
  readonly "outcome": DeviceProviderOutcome
  readonly "requestId": string
  readonly "revision": number
}

export type DeviceProviderReport = {
  readonly "receipt": DeviceProviderReceipt | null
  readonly "snapshot": DeviceProviderSnapshot
}

export type DeviceProviderSnapshot = {
  readonly "clientNodeId": string
  readonly "encryptionPublicKey": string
  readonly "providers": ReadonlyArray<DeviceProviderProjection>
  readonly "revision": number
}
