// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-contracts.mjs. Do not edit.
// Source digest: sha256:a08b95781a3d93af9811d0a391dd39002ef2c1f9384f5e4cf4247163446e2326

#![allow(clippy::doc_markdown)]

//! Shared identifiers and value objects generated from the canonical schemas.

#[allow(clippy::missing_errors_doc)]
fn deserialize_required_nullable<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    <Option<T> as serde::Deserialize>::deserialize(deserializer)
}

/// Stable Worker-and-role-derived Agent identity.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct AgentIdentityId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ApiTokenId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ApprovalId(pub String);

/// Identity of one lease-scoped execution artifact.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ArtifactId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct AttentionItemId(pub String);

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Candidate {
    #[serde(rename = "attempt")]
    pub attempt: i64,
    #[serde(rename = "baseCommit")]
    pub base_commit: String,
    #[serde(rename = "candidateCommit")]
    pub candidate_commit: String,
    #[serde(rename = "candidateDigest")]
    pub candidate_digest: CandidateDigest,
    #[serde(rename = "candidateRef")]
    pub candidate_ref: String,
    #[serde(rename = "candidateTree")]
    pub candidate_tree: String,
    #[serde(rename = "contractRevision")]
    pub contract_revision: Revision,
    #[serde(rename = "diffDigest")]
    pub diff_digest: Sha256Digest,
    #[serde(rename = "id")]
    pub id: CandidateId,
    #[serde(rename = "producerWorkerSessionId")]
    pub producer_worker_session_id: WorkerSessionId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: SchemaVersion,
    #[serde(rename = "workContractId")]
    pub work_contract_id: WorkContractId,
    #[serde(rename = "workItemId")]
    pub work_item_id: WorkItemId,
    #[serde(rename = "workRunId")]
    pub work_run_id: WorkRunId,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct CandidateDigest(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct CandidateId(pub String);

/// Stable local git ref that survives worktree cleanup.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct CandidateRef(pub String);

/// Content-derived identity of one ChangeBatch: SHA-256 over the canonical run key, turn id, optional call id, and patch digest.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ChangeBatchId(pub String);

/// User attachment: UTF-8 text (32 KiB each) or base64 PNG/JPEG/WebP. Up to four and 128 KiB decoded total per message.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ChatAttachment {
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "mediaType")]
    pub media_type: String,
    #[serde(rename = "name")]
    pub name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ChatMessageId(pub String);

/// Identity of one user-to-client access grant.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientAccessGrantId(pub String);

/// Identity of one one-time dynamic connect code publication.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientConnectCodeId(pub String);

/// Unique identity of one ClientControlPort message envelope.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientControlMessageId(pub String);

/// User-chosen display name for a ClientNode or repository binding.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientDisplayName(pub String);

/// Strictly increasing per-client exchange stream position used for acknowledgement and replay.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientExchangeSequence(pub i64);

/// Identity of one Device Client process boot; changes after every restart.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientInstanceId(pub String);

/// Identity of one registered Device Client node.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientNodeId(pub String);

/// Identity of one exclusive occupancy lease. At most one active lease exists per ClientNode.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientOccupancyLeaseId(pub String);

/// Device Client semantic version.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientVersion(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct CodexThreadId(pub String);

/// Stable identity of one persisted Control Plane event, independent of transport.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ControlPlaneEventId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ControlPlaneWebSocketAuthorizationEpoch(pub i64);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ControlPlaneWebSocketEventSequence(pub i64);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ControlPlaneWebSocketSubscriptionId(pub String);

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CoreToolAgentWaitProjection {
    #[serde(rename = "edge")]
    pub edge: CoreToolWaitEdgeProjection,
    #[serde(rename = "state")]
    pub state: CoreToolWaitState,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CoreToolCallProjection {
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "attemptId")]
    pub attempt_id: Option<String>,
    #[serde(rename = "cancelled")]
    pub cancelled: bool,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "cellId")]
    pub cell_id: Option<String>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "delivery")]
    pub delivery: Option<CoreToolOutputDelivery>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "disposition")]
    pub disposition: Option<CoreToolOutputDisposition>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "execution")]
    pub execution: Option<CoreToolExecutionState>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "inputValidation")]
    pub input_validation: Option<CoreToolInputValidation>,
    #[serde(rename = "logicalId")]
    pub logical_id: String,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "parentCallId")]
    pub parent_call_id: Option<String>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "parentRequestSequence")]
    pub parent_request_sequence: Option<ExecutionSequence>,
    #[serde(rename = "requestSequence")]
    pub request_sequence: ExecutionSequence,
    #[serde(rename = "toolName")]
    pub tool_name: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CoreToolCallReference {
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "cellId")]
    pub cell_id: Option<String>,
    #[serde(rename = "logicalId")]
    pub logical_id: String,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "parentCallId")]
    pub parent_call_id: Option<String>,
    #[serde(rename = "requestSequence")]
    pub request_sequence: ExecutionSequence,
    #[serde(rename = "toolName")]
    pub tool_name: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum CoreToolCellLifecycle {
    #[serde(rename = "live")]
    Live,
    #[serde(rename = "closed")]
    Closed,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CoreToolCellProjection {
    #[serde(rename = "cellId")]
    pub cell_id: String,
    #[serde(rename = "lifecycle")]
    pub lifecycle: CoreToolCellLifecycle,
    #[serde(rename = "parentRequestSequence")]
    pub parent_request_sequence: ExecutionSequence,
    #[serde(rename = "sequence")]
    pub sequence: ExecutionSequence,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum CoreToolDiagnosticDelivery {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "offered")]
    Offered,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum CoreToolDiagnosticKind {
    #[serde(rename = "repeated_operation")]
    RepeatedOperation,
    #[serde(rename = "alternating_cycle")]
    AlternatingCycle,
    #[serde(rename = "branch_expansion")]
    BranchExpansion,
    #[serde(rename = "wait_cycle")]
    WaitCycle,
    #[serde(rename = "unavailable_wait")]
    UnavailableWait,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CoreToolDiagnosticProjection {
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "delivery")]
    pub delivery: Option<CoreToolDiagnosticDelivery>,
    #[serde(rename = "diagnosticId")]
    pub diagnostic_id: String,
    #[serde(rename = "evidence")]
    pub evidence: Vec<CoreToolCallReference>,
    #[serde(rename = "evidenceVersion")]
    pub evidence_version: ExecutionSequence,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "kind")]
    pub kind: Option<CoreToolDiagnosticKind>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "question")]
    pub question: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "waitGraph")]
    pub wait_graph: Option<Vec<CoreToolWaitEdgeProjection>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum CoreToolExecutionState {
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "uncertain")]
    Uncertain,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum CoreToolFactKind {
    #[serde(rename = "request")]
    Request,
    #[serde(rename = "cell")]
    Cell,
    #[serde(rename = "wait")]
    Wait,
    #[serde(rename = "reconciliation")]
    Reconciliation,
    #[serde(rename = "diagnostic")]
    Diagnostic,
    #[serde(rename = "progress")]
    Progress,
    #[serde(rename = "diagnostic_response")]
    DiagnosticResponse,
    #[serde(rename = "sharing")]
    Sharing,
    #[serde(rename = "waiter_cancellation")]
    WaiterCancellation,
    #[serde(rename = "input_binding")]
    InputBinding,
    #[serde(rename = "input_validation")]
    InputValidation,
    #[serde(rename = "agent_wait")]
    AgentWait,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum CoreToolInputValidation {
    #[serde(rename = "verified")]
    Verified,
    #[serde(rename = "mismatch")]
    Mismatch,
    #[serde(rename = "unknown")]
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum CoreToolOutputDelivery {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "offered")]
    Offered,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum CoreToolOutputDisposition {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "accepted")]
    Accepted,
    #[serde(rename = "rejected")]
    Rejected,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CoreToolRecoveryProjection {
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "businessId")]
    pub business_id: Option<String>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "exitCode")]
    pub exit_code: Option<i64>,
    #[serde(rename = "requestSequence")]
    pub request_sequence: ExecutionSequence,
    #[serde(rename = "state")]
    pub state: CoreToolRecoveryState,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum CoreToolRecoveryState {
    #[serde(rename = "unavailable")]
    Unavailable,
    #[serde(rename = "unconfirmed")]
    Unconfirmed,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "exited")]
    Exited,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CoreToolRuntimeProjection {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "agentWait")]
    pub agent_wait: Option<CoreToolAgentWaitProjection>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "call")]
    pub call: Option<CoreToolCallProjection>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "cell")]
    pub cell: Option<CoreToolCellProjection>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "diagnosis")]
    pub diagnosis: Option<CoreToolDiagnosticProjection>,
    #[serde(rename = "kind")]
    pub kind: CoreToolFactKind,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "recovery")]
    pub recovery: Option<CoreToolRecoveryProjection>,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "sharing")]
    pub sharing: Option<CoreToolSharingProjection>,
    #[serde(rename = "sourceSequence")]
    pub source_sequence: ExecutionSequence,
    #[serde(rename = "sourceThreadId")]
    pub source_thread_id: String,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "wait")]
    pub wait: Option<CoreToolWaitProjection>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum CoreToolSharingKind {
    #[serde(rename = "reuse")]
    Reuse,
    #[serde(rename = "merged")]
    Merged,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CoreToolSharingProjection {
    #[serde(rename = "kind")]
    pub kind: CoreToolSharingKind,
    #[serde(rename = "sourceAttemptId")]
    pub source_attempt_id: String,
    #[serde(rename = "sourceRequestSequence")]
    pub source_request_sequence: ExecutionSequence,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CoreToolWaitEdgeProjection {
    #[serde(rename = "deadlineUnixMs")]
    pub deadline_unix_ms: i64,
    #[serde(rename = "logicalId")]
    pub logical_id: String,
    #[serde(rename = "requestSequence")]
    pub request_sequence: ExecutionSequence,
    #[serde(rename = "source")]
    pub source: CoreToolWaitNodeProjection,
    #[serde(rename = "targetCount")]
    pub target_count: i64,
    #[serde(rename = "targets")]
    pub targets: Vec<CoreToolWaitNodeProjection>,
    #[serde(rename = "treeId")]
    pub tree_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum CoreToolWaitNodeKind {
    #[serde(rename = "thread")]
    Thread,
    #[serde(rename = "cell")]
    Cell,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CoreToolWaitNodeProjection {
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "cellId")]
    pub cell_id: Option<String>,
    #[serde(rename = "kind")]
    pub kind: CoreToolWaitNodeKind,
    #[serde(rename = "ownerId")]
    pub owner_id: String,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "scopeId")]
    pub scope_id: Option<String>,
    #[serde(rename = "threadId")]
    pub thread_id: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CoreToolWaitProjection {
    #[serde(rename = "requestSequence")]
    pub request_sequence: ExecutionSequence,
    #[serde(rename = "state")]
    pub state: CoreToolWaitState,
    #[serde(rename = "targetCellSequence")]
    pub target_cell_sequence: ExecutionSequence,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum CoreToolWaitState {
    #[serde(rename = "waiting")]
    Waiting,
    #[serde(rename = "settled")]
    Settled,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct Count(pub i64);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct CredentialReferenceId(pub String);

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Criterion {
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "id")]
    pub id: CriterionId,
    #[serde(rename = "required")]
    pub required: bool,
    /// Evidence class required by the current Community verifier. Model narrative is not machine evidence.
    #[serde(rename = "requiredEvidenceClass")]
    pub required_evidence_class: String,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "verificationMethod")]
    pub verification_method: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct CriterionId(pub String);

/// Identity of one isolated ephemeral debug experiment.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct DebugExperimentId(pub String);

/// Identity of one hypothesis tracked by a DebugProbe ledger.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct DebugHypothesisId(pub String);

/// Identity of one durable DebugProbe session.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct DebugSessionId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct DeliveryId(pub String);

/// Last persisted sequence included in a snapshot or event-stream baseline; zero represents an empty stream.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct EventReadPosition(pub i64);

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Evidence {
    #[serde(rename = "attempt")]
    pub attempt: i64,
    #[serde(rename = "candidateId")]
    pub candidate_id: CandidateId,
    #[serde(rename = "contractRevision")]
    pub contract_revision: Revision,
    #[serde(rename = "createdAt")]
    pub created_at: Instant,
    #[serde(rename = "criterionId")]
    pub criterion_id: CriterionId,
    #[serde(rename = "id")]
    pub id: EvidenceId,
    #[serde(rename = "outcome")]
    pub outcome: String,
    #[serde(rename = "planRevision")]
    pub plan_revision: Revision,
    #[serde(rename = "producer")]
    pub producer: String,
    #[serde(rename = "producerExecutionIdentity")]
    pub producer_execution_identity: ExecutionFactIdentity,
    #[serde(rename = "schemaVersion")]
    pub schema_version: SchemaVersion,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: SessionIdentity,
    #[serde(rename = "snapshotId")]
    pub snapshot_id: SnapshotId,
    #[serde(rename = "sourceEventId")]
    pub source_event_id: String,
    #[serde(rename = "sourceSequence")]
    pub source_sequence: i64,
    #[serde(rename = "verificationPlanId")]
    pub verification_plan_id: VerificationPlanId,
    #[serde(rename = "verificationSessionId")]
    pub verification_session_id: VerificationSessionId,
    #[serde(rename = "workContractId")]
    pub work_contract_id: WorkContractId,
    #[serde(rename = "workItemId")]
    pub work_item_id: WorkItemId,
    #[serde(rename = "workRunId")]
    pub work_run_id: WorkRunId,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct EvidenceId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ExecutionAckSequence(pub i64);

/// Stable identity retained when a runtime event is replayed.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ExecutionEventId(pub String);

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ExecutionFactIdentity {
    #[serde(rename = "attempt")]
    pub attempt: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "codexThreadId")]
    pub codex_thread_id: Option<CodexThreadId>,
    #[serde(rename = "executionJobId")]
    pub execution_job_id: ExecutionJobId,
    #[serde(rename = "fencingToken")]
    pub fencing_token: String,
    #[serde(rename = "leaseId")]
    pub lease_id: LeaseId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "productSessionId")]
    pub product_session_id: Option<ProductSessionId>,
    #[serde(rename = "workerId")]
    pub worker_id: WorkerId,
    #[serde(rename = "workerInstanceId")]
    pub worker_instance_id: WorkerInstanceId,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: WorkerSessionId,
}

/// Identity of one scheduler-owned execution job.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ExecutionJobId(pub String);

/// Unique identity of one ExecutionPort message envelope.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ExecutionMessageId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ExecutionSequence(pub i64);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ExternalIdentityId(pub String);

/// Monotonically increasing decimal token encoded as a string to preserve 64-bit precision.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct FencingToken(pub String);

/// Full git commit object name in SHA-1 or SHA-256 form.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct GitCommitSha(pub String);

/// GitHub owner/repository without URL syntax, userinfo, query, fragment, or credentials.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct GitHubRepositorySlug(pub String);

/// Exact SHA-1 or SHA-256 Git object identity.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct GitObjectId(pub String);

/// Git branch or ref name as accepted by git check-ref-format. Full git ref-format rules are enforced by git itself.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct GitRefName(pub String);

/// Opaque retry identity of one command; the same key with the same payload replays the first result.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct IdempotencyKey(pub String);

/// Identity of one interactive input request.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct InputRequestId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct Instant(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct IntegrationId(pub String);

/// Stable identity of one choice within an interactive input request.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct InteractiveInputChoiceId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum InteractiveInputMode {
    #[serde(rename = "confirmation")]
    Confirmation,
    #[serde(rename = "single_choice")]
    SingleChoice,
    #[serde(rename = "text")]
    Text,
}

/// Bound user response value; never an ExecutionPort message or command payload.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct InteractiveInputValue {
    #[serde(rename = "mode")]
    pub mode: InteractiveInputMode,
    #[serde(rename = "value")]
    pub value: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct LeaseId(pub String);

/// Identity of one client-issued local apply receipt.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct LocalApplyReceiptId(pub String);

/// Identity of one client-issued candidate retention receipt.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct LocalCandidateReceiptId(pub String);

/// Identity of one provider-neutral model stream exchange.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ModelExchangeId(pub String);

/// Content-derived identity of one ChangeBatch observation intent.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ObservationId(pub String);

/// Identity of one atomic occupancy claim attempt.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct OccupancyClaimId(pub String);

/// Monotonically increasing occupancy fencing token encoded as a string to preserve 64-bit precision. Every new occupancy mints a higher token; stale tokens are always rejected.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct OccupancyFencingToken(pub String);

/// Opaque cursor bound to scope, query, filters, and one stable snapshot.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct OpaqueCursor(pub String);

/// Protocol scope-key identifier. In WinWinCode Community this is the local Owner scope encoding used by LocalDefaultScope, not multi-tenant organization membership.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct OrganizationId(pub String);

/// Content-derived identity of one exact scheduled probe execution, including its authority and probe definition digest.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ProbeExecutionId(pub String);

/// Identity of one probe definition within a DebugProbe round.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ProbeId(pub String);

/// Identity of one bounded DebugProbe round.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ProbeRoundId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ProductSessionId(pub String);

/// Protocol scope-key identifier. Community product identity uses LocalDefaultScope; this key is not multi-tenant project membership.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ProjectId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct PublicationId(pub String);

/// Stable user-visible Client ID used to look up a pending or active ClientNode. It is public and never a credential.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct PublicClientId(pub String);

/// Identity of one user-to-repository access grant.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct RepositoryAccessGrantId(pub String);

/// Identity of one ClientNode-local repository binding. The absolute local path stays in the Device Client local database and never crosses this contract.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct RepositoryBindingId(pub String);

/// Protocol scope-key identifier. Community product identity uses LocalDefaultScope; this key is not multi-tenant repository administration.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct RepositoryId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum RepositoryScopeKind {
    #[serde(rename = "repository")]
    Repository,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RepositoryScope {
    #[serde(rename = "kind")]
    pub kind: RepositoryScopeKind,
    #[serde(rename = "organizationId")]
    pub organization_id: OrganizationId,
    #[serde(rename = "projectId")]
    pub project_id: ProjectId,
    #[serde(rename = "repositoryId")]
    pub repository_id: RepositoryId,
    #[serde(rename = "workspaceId")]
    pub workspace_id: WorkspaceId,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct RequestId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct Revision(pub i64);

/// Secret-free stable Agent identity frozen when the embedded runtime opens a Session.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RuntimeSessionAgentIdentity {
    #[serde(rename = "id")]
    pub id: AgentIdentityId,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "workerId")]
    pub worker_id: WorkerId,
}

/// Secret-free immutable runtime facts reported by the Worker for one opened Session.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RuntimeSessionContext {
    #[serde(rename = "agentIdentity")]
    pub agent_identity: RuntimeSessionAgentIdentity,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "workspace")]
    pub workspace: RuntimeSessionWorkspace,
}

/// Exact detached repository workspace identity without a device-local path.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RuntimeSessionWorkspace {
    #[serde(rename = "repositoryId")]
    pub repository_id: RepositoryId,
    #[serde(rename = "revision")]
    pub revision: WorkspaceRevision,
    #[serde(rename = "writeMode")]
    pub write_mode: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum SchemaVersion {
    #[serde(rename = "winwincode/v1")]
    WinwincodeV1,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ServiceAccountId(pub String);

/// Stable source identity that produced a SessionBinding.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum SessionBindingSourceIdentityKind {
    #[serde(rename = "execution-worker")]
    ExecutionWorker,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SessionBindingSourceIdentity {
    #[serde(rename = "kind")]
    pub kind: SessionBindingSourceIdentityKind,
    #[serde(rename = "leaseId")]
    pub lease_id: LeaseId,
    #[serde(rename = "workerId")]
    pub worker_id: WorkerId,
    #[serde(rename = "workerInstanceId")]
    pub worker_instance_id: WorkerInstanceId,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: WorkerSessionId,
}

/// Identity of one executable session. WorkRun sessions carry WorkRunId; ProductSession Chat sessions omit it.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SessionIdentity {
    #[serde(rename = "codexThreadId")]
    pub codex_thread_id: CodexThreadId,
    #[serde(rename = "productSessionId")]
    pub product_session_id: ProductSessionId,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: WorkerSessionId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "workRunId")]
    pub work_run_id: Option<WorkRunId>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct Sha256Digest(pub String);

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Snapshot {
    #[serde(rename = "baseCommitId")]
    pub base_commit_id: GitObjectId,
    #[serde(rename = "baseTreeId")]
    pub base_tree_id: GitObjectId,
    #[serde(rename = "candidateCommitId")]
    pub candidate_commit_id: GitObjectId,
    #[serde(rename = "candidateId")]
    pub candidate_id: CandidateId,
    #[serde(rename = "candidateTreeId")]
    pub candidate_tree_id: GitObjectId,
    #[serde(rename = "contentDigest")]
    pub content_digest: Sha256Digest,
    #[serde(rename = "createdAtMillis")]
    pub created_at_millis: i64,
    #[serde(rename = "diffSha256")]
    pub diff_sha256: Sha256Digest,
    #[serde(rename = "immutable")]
    pub immutable: bool,
    #[serde(rename = "repositoryId")]
    pub repository_id: RepositoryId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: SchemaVersion,
    #[serde(rename = "snapshotId")]
    pub snapshot_id: SnapshotId,
    #[serde(rename = "validationSeal")]
    pub validation_seal: Sha256Digest,
    #[serde(rename = "workRunId")]
    pub work_run_id: WorkRunId,
}

/// Canonical ULID for one immutable code snapshot under verification.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct SnapshotId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct SystemActorId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum UserActorKind {
    #[serde(rename = "user")]
    User,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UserActor {
    #[serde(rename = "id")]
    pub id: UserId,
    #[serde(rename = "kind")]
    pub kind: UserActorKind,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct UserId(pub String);

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Verdict {
    #[serde(rename = "attempt")]
    pub attempt: i64,
    #[serde(rename = "candidateId")]
    pub candidate_id: CandidateId,
    #[serde(rename = "contractRevision")]
    pub contract_revision: Revision,
    #[serde(rename = "createdAt")]
    pub created_at: Instant,
    #[serde(rename = "evidenceIds")]
    pub evidence_ids: Vec<EvidenceId>,
    #[serde(rename = "id")]
    pub id: VerdictId,
    #[serde(rename = "planRevision")]
    pub plan_revision: Revision,
    #[serde(rename = "revision")]
    pub revision: Revision,
    #[serde(rename = "schemaVersion")]
    pub schema_version: SchemaVersion,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: SessionIdentity,
    #[serde(rename = "snapshotId")]
    pub snapshot_id: SnapshotId,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "verificationPlanId")]
    pub verification_plan_id: VerificationPlanId,
    #[serde(rename = "verificationSessionId")]
    pub verification_session_id: VerificationSessionId,
    #[serde(rename = "workContractId")]
    pub work_contract_id: WorkContractId,
    #[serde(rename = "workItemId")]
    pub work_item_id: WorkItemId,
    #[serde(rename = "workRunId")]
    pub work_run_id: WorkRunId,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct VerdictId(pub String);

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VerificationPlan {
    #[serde(rename = "candidateDigest")]
    pub candidate_digest: CandidateDigest,
    #[serde(rename = "commands")]
    pub commands: Vec<String>,
    #[serde(rename = "contractRevision")]
    pub contract_revision: Revision,
    #[serde(rename = "criterionIds")]
    pub criterion_ids: Vec<CriterionId>,
    #[serde(rename = "id")]
    pub id: VerificationPlanId,
    #[serde(rename = "permissionProfile")]
    pub permission_profile: String,
    #[serde(rename = "planRevision")]
    pub plan_revision: Revision,
    #[serde(rename = "requiredRoles")]
    pub required_roles: Vec<String>,
    #[serde(rename = "schemaVersion")]
    pub schema_version: SchemaVersion,
    #[serde(rename = "workContractId")]
    pub work_contract_id: WorkContractId,
    #[serde(rename = "workItemId")]
    pub work_item_id: WorkItemId,
    #[serde(rename = "workItemRevision")]
    pub work_item_revision: Revision,
    #[serde(rename = "workRunId")]
    pub work_run_id: WorkRunId,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct VerificationPlanId(pub String);

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VerificationSession {
    #[serde(rename = "attempt")]
    pub attempt: i64,
    #[serde(rename = "candidateId")]
    pub candidate_id: CandidateId,
    #[serde(rename = "createdAt")]
    pub created_at: Instant,
    #[serde(rename = "id")]
    pub id: VerificationSessionId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: SchemaVersion,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: SessionIdentity,
    #[serde(rename = "snapshotId")]
    pub snapshot_id: SnapshotId,
    #[serde(rename = "verificationPlanId")]
    pub verification_plan_id: VerificationPlanId,
    #[serde(rename = "verificationSessionId")]
    pub verification_session_id: VerificationSessionId,
    #[serde(rename = "workRunId")]
    pub work_run_id: WorkRunId,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct VerificationSessionId(pub String);

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VerifierResult {
    #[serde(rename = "attempt")]
    pub attempt: i64,
    #[serde(rename = "candidateId")]
    pub candidate_id: CandidateId,
    #[serde(rename = "createdAt")]
    pub created_at: Instant,
    #[serde(rename = "evidenceIds")]
    pub evidence_ids: Vec<EvidenceId>,
    #[serde(rename = "id")]
    pub id: VerifierResultId,
    #[serde(rename = "schemaVersion")]
    pub schema_version: SchemaVersion,
    #[serde(rename = "sessionIdentity")]
    pub session_identity: SessionIdentity,
    #[serde(rename = "snapshotId")]
    pub snapshot_id: SnapshotId,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "verificationPlanId")]
    pub verification_plan_id: VerificationPlanId,
    #[serde(rename = "verificationSessionId")]
    pub verification_session_id: VerificationSessionId,
    #[serde(rename = "workRunId")]
    pub work_run_id: WorkRunId,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct VerifierResultId(pub String);

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkContract {
    #[serde(rename = "constraints")]
    pub constraints: Vec<String>,
    #[serde(rename = "createdAt")]
    pub created_at: Instant,
    #[serde(rename = "criteria")]
    pub criteria: Vec<Criterion>,
    #[serde(rename = "id")]
    pub id: WorkContractId,
    #[serde(rename = "objective")]
    pub objective: String,
    #[serde(rename = "protectedScope")]
    pub protected_scope: Vec<String>,
    #[serde(rename = "requiredHumanAuthority")]
    pub required_human_authority: String,
    #[serde(rename = "revision")]
    pub revision: Revision,
    #[serde(rename = "schemaVersion")]
    pub schema_version: SchemaVersion,
    #[serde(rename = "scope")]
    pub scope: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct WorkContractId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct WorkerId(pub String);

/// Identity of one Worker process boot; changes after every restart.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct WorkerInstanceId(pub String);

/// Identity of one single-use worker launch grant.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct WorkerLaunchGrantId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct WorkerSessionId(pub String);

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkItem {
    #[serde(rename = "criterionIds")]
    pub criterion_ids: Vec<CriterionId>,
    #[serde(rename = "dependsOn")]
    pub depends_on: Vec<WorkItemId>,
    #[serde(rename = "goal")]
    pub goal: String,
    #[serde(rename = "id")]
    pub id: WorkItemId,
    #[serde(rename = "revision")]
    pub revision: Revision,
    #[serde(rename = "schemaVersion")]
    pub schema_version: SchemaVersion,
    #[serde(rename = "state")]
    pub state: WorkItemState,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "workContractId")]
    pub work_contract_id: WorkContractId,
    #[serde(rename = "workContractRevision")]
    pub work_contract_revision: Revision,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct WorkItemId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum WorkItemState {
    #[serde(rename = "backlog")]
    Backlog,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "waiting_dependency")]
    WaitingDependency,
    #[serde(rename = "waiting_human")]
    WaitingHuman,
    #[serde(rename = "candidate_ready")]
    CandidateReady,
    #[serde(rename = "validating")]
    Validating,
    #[serde(rename = "rework")]
    Rework,
    #[serde(rename = "done")]
    Done,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "cancelled")]
    Cancelled,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorkRun {
    #[serde(rename = "attempt")]
    pub attempt: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "candidateDigest")]
    pub candidate_digest: Option<CandidateDigest>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "codexThreadId")]
    pub codex_thread_id: Option<CodexThreadId>,
    #[serde(rename = "contractRevision")]
    pub contract_revision: Revision,
    #[serde(rename = "executionJobId")]
    pub execution_job_id: ExecutionJobId,
    #[serde(rename = "fencingToken")]
    pub fencing_token: String,
    #[serde(rename = "id")]
    pub id: WorkRunId,
    #[serde(rename = "leaseId")]
    pub lease_id: LeaseId,
    #[serde(deserialize_with = "deserialize_required_nullable")]
    #[serde(rename = "productSessionId")]
    pub product_session_id: Option<ProductSessionId>,
    #[serde(rename = "revision")]
    pub revision: Revision,
    #[serde(rename = "schemaVersion")]
    pub schema_version: SchemaVersion,
    #[serde(rename = "state")]
    pub state: WorkRunState,
    #[serde(rename = "workContractId")]
    pub work_contract_id: WorkContractId,
    #[serde(rename = "workerId")]
    pub worker_id: WorkerId,
    #[serde(rename = "workerInstanceId")]
    pub worker_instance_id: WorkerInstanceId,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: WorkerSessionId,
    #[serde(rename = "workItemId")]
    pub work_item_id: WorkItemId,
    #[serde(rename = "workItemRevision")]
    pub work_item_revision: Revision,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct WorkRunId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum WorkRunState {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "leased")]
    Leased,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "candidate_ready")]
    CandidateReady,
    #[serde(rename = "settled")]
    Settled,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "cancelled")]
    Cancelled,
}

/// Protocol scope-key identifier. Community product identity uses LocalDefaultScope; this key is not Cloud/Enterprise workspace administration.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct WorkspaceId(pub String);

/// Exact Git tree object identity for a workspace snapshot. SHA-1 repositories use 40 lowercase hexadecimal digits and SHA-256 repositories use 64.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize)]
#[serde(transparent)]
pub struct WorkspaceRevision(pub String);

impl<'de> serde::Deserialize<'de> for WorkspaceRevision {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <String as serde::Deserialize>::deserialize(deserializer)?;
        let Some(object_id) = value.strip_prefix("git-tree:") else {
            return Err(serde::de::Error::custom(
                "WorkspaceRevision must start with git-tree:",
            ));
        };
        if !matches!(object_id.len(), 40 | 64)
            || !object_id
                .bytes()
                .all(|byte| byte.is_ascii_digit() || matches!(byte, b'a'..=b'f'))
        {
            return Err(serde::de::Error::custom(
                "WorkspaceRevision must contain a 40- or 64-digit lowercase Git tree object id",
            ));
        }
        Ok(Self(value))
    }
}
