// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-contracts.mjs. Do not edit.
// Source digest: sha256:d75bba709d5a709d360f41aa45786e2b178cbc6abf97f6c526e6bf1ef2c93866

#![allow(clippy::doc_markdown)]

//! Shared identifiers and value objects generated from the canonical schemas.

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ApiTokenId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ApprovalId(pub String);

/// Identity of one lease-scoped execution artifact.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ArtifactId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct AttentionItemId(pub String);

/// Stable local git ref that survives worktree cleanup.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct CandidateRef(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ChatMessageId(pub String);

/// Identity of one pending access challenge sent to the Device Client before a grant is created.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientAccessChallengeId(pub String);

/// Identity of one user-to-client access grant.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientAccessGrantId(pub String);

/// Identity of one one-time dynamic connect code publication.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientConnectCodeId(pub String);

/// Unique identity of one ClientControlPort message envelope.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientControlMessageId(pub String);

/// User-chosen display name for a ClientNode or repository binding.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientDisplayName(pub String);

/// Strictly increasing per-client exchange stream position used for acknowledgement and replay.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientExchangeSequence(pub i64);

/// Identity of one Device Client process boot; changes after every restart.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientInstanceId(pub String);

/// Identity of one registered Device Client node.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientNodeId(pub String);

/// Identity of one exclusive occupancy lease. At most one active lease exists per ClientNode.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientOccupancyLeaseId(pub String);

/// Device Client semantic version.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ClientVersion(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct CodexThreadId(pub String);

/// Stable identity of one persisted Control Plane event, independent of transport.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ControlPlaneEventId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ControlPlaneWebSocketAuthorizationEpoch(pub i64);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ControlPlaneWebSocketEventSequence(pub i64);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ControlPlaneWebSocketSubscriptionId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct Count(pub i64);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct CredentialReferenceId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct DeliveryId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct DeliveryTaskId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct EnterpriseIntegrationId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct EnterpriseMembershipId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct EnterprisePolicyId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct EnterpriseRoleId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct EnterpriseRoleVersion(pub i64);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct EnterpriseTeamId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct EnterpriseWorkerPoolId(pub String);

/// Last persisted sequence included in a snapshot or event-stream baseline; zero represents an empty stream.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct EventReadPosition(pub i64);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct EvidenceId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ExecutionAckSequence(pub i64);

/// Stable identity retained when a runtime event is replayed.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ExecutionEventId(pub String);

/// Identity of one scheduler-owned execution job.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ExecutionJobId(pub String);

/// Unique identity of one ExecutionPort message envelope.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ExecutionMessageId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ExecutionSequence(pub i64);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ExternalIdentityId(pub String);

/// Monotonically increasing decimal token encoded as a string to preserve 64-bit precision.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct FencingToken(pub String);

/// Full git commit object name in SHA-1 or SHA-256 form.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct GitCommitSha(pub String);

/// GitHub owner/repository without URL syntax, userinfo, query, fragment, or credentials.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct GitHubRepositorySlug(pub String);

/// Git branch or ref name as accepted by git check-ref-format. Full git ref-format rules are enforced by git itself.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct GitRefName(pub String);

/// Opaque retry identity of one command; the same key with the same payload replays the first result.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct IdempotencyKey(pub String);

/// Identity of one interactive input request.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct InputRequestId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct Instant(pub String);

/// Stable identity of one choice within an interactive input request.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct InteractiveInputChoiceId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum InteractiveInputMode {
    #[serde(rename = "confirmation")]
    Confirmation,
    #[serde(rename = "single_choice")]
    SingleChoice,
    #[serde(rename = "text")]
    Text,
}

/// Bound user response value; never an ExecutionPort message or command payload.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct InteractiveInputValue {
    #[serde(rename = "mode")]
    pub mode: InteractiveInputMode,
    #[serde(rename = "value")]
    pub value: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct LeaseId(pub String);

/// Identity of one client-issued local apply receipt.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct LocalApplyReceiptId(pub String);

/// Identity of one client-issued candidate retention receipt.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct LocalCandidateReceiptId(pub String);

/// Identity of one provider-neutral model stream exchange.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ModelExchangeId(pub String);

/// Identity of one atomic occupancy claim attempt.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct OccupancyClaimId(pub String);

/// Monotonically increasing occupancy fencing token encoded as a string to preserve 64-bit precision. Every new occupancy mints a higher token; stale tokens are always rejected.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct OccupancyFencingToken(pub String);

/// Opaque cursor bound to scope, query, filters, and one stable snapshot.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct OpaqueCursor(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct OrganizationId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ProductSessionId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ProjectId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct PublicationId(pub String);

/// Stable user-visible Client ID used to look up a pending or active ClientNode. It is public and never a credential.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct PublicClientId(pub String);

/// Identity of one user-to-repository access grant.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct RepositoryAccessGrantId(pub String);

/// Identity of one ClientNode-local repository binding. The absolute local path stays in the Device Client local database and never crosses this contract.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct RepositoryBindingId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct RepositoryId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum RepositoryScopeKind {
    #[serde(rename = "repository")]
    Repository,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RepositoryScope {
    #[serde(rename = "kind")]
    pub kind: RepositoryScopeKind,
    #[serde(rename = "organizationId")]
    pub organization_id: OrganizationId,
    #[serde(rename = "projectId")]
    pub project_id: ProjectId,
    #[serde(rename = "repositoryId")]
    pub repository_id: RepositoryId,
    #[serde(rename = "workspaceId")]
    pub workspace_id: WorkspaceId,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct RequestId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct Revision(pub i64);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum SchemaVersion {
    #[serde(rename = "winwincode/v1")]
    WinwincodeV1,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct ServiceAccountId(pub String);

/// Stable source identity that produced a SessionBinding.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum SessionBindingSourceIdentityKind {
    #[serde(rename = "execution-worker")]
    ExecutionWorker,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SessionBindingSourceIdentity {
    #[serde(rename = "kind")]
    pub kind: SessionBindingSourceIdentityKind,
    #[serde(rename = "leaseId")]
    pub lease_id: LeaseId,
    #[serde(rename = "workerId")]
    pub worker_id: WorkerId,
    #[serde(rename = "workerInstanceId")]
    pub worker_instance_id: WorkerInstanceId,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: WorkerSessionId,
}

/// Identity of one executable session. Delivery-stage sessions carry StageRun; ProductSession Chat sessions omit it.
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SessionIdentity {
    #[serde(rename = "codexThreadId")]
    pub codex_thread_id: CodexThreadId,
    #[serde(rename = "productSessionId")]
    pub product_session_id: ProductSessionId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[serde(rename = "stageRunId")]
    pub stage_run_id: Option<StageRunId>,
    #[serde(rename = "workerSessionId")]
    pub worker_session_id: WorkerSessionId,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct Sha256Digest(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct StageRunId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct SystemActorId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum UserActorKind {
    #[serde(rename = "user")]
    User,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct UserActor {
    #[serde(rename = "id")]
    pub id: UserId,
    #[serde(rename = "kind")]
    pub kind: UserActorKind,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct UserId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct WorkerId(pub String);

/// Identity of one Worker process boot; changes after every restart.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct WorkerInstanceId(pub String);

/// Identity of one single-use worker launch grant.
#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct WorkerLaunchGrantId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct WorkerSessionId(pub String);

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(transparent)]
pub struct WorkspaceId(pub String);
